/*
NewsCatcher-V3 Production API

<img src='https://uploads-ssl.webflow.com/6429857b17973b636c2195c5/646c6f1eb774ff2f2997bec5_newscatcher_.svg' width='286' height='35' /> <br>  <br>Visit our website  <a href='https://newscatcherapi.com'>https://newscatcherapi.com</a>

API version: 3.2.16
Contact: maksym@newscatcherapi.com
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package newscatcherapi

import (
	"encoding/json"
	"fmt"
)

// SearchduplicatesbyoriginalidPostResponse struct for SearchduplicatesbyoriginalidPostResponse
type SearchduplicatesbyoriginalidPostResponse struct {
	ClusteringSearchResponse *ClusteringSearchResponse
	DtoResponsesSearchResponseSearchResponse *DtoResponsesSearchResponseSearchResponse
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SearchduplicatesbyoriginalidPostResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ClusteringSearchResponse
	err = json.Unmarshal(data, &dst.ClusteringSearchResponse);
	if err == nil {
		jsonClusteringSearchResponse, _ := json.Marshal(dst.ClusteringSearchResponse)
		if string(jsonClusteringSearchResponse) == "{}" { // empty struct
			dst.ClusteringSearchResponse = nil
		} else {
			return nil // data stored in dst.ClusteringSearchResponse, return on the first match
		}
	} else {
		dst.ClusteringSearchResponse = nil
	}

	// try to unmarshal JSON data into DtoResponsesSearchResponseSearchResponse
	err = json.Unmarshal(data, &dst.DtoResponsesSearchResponseSearchResponse);
	if err == nil {
		jsonDtoResponsesSearchResponseSearchResponse, _ := json.Marshal(dst.DtoResponsesSearchResponseSearchResponse)
		if string(jsonDtoResponsesSearchResponseSearchResponse) == "{}" { // empty struct
			dst.DtoResponsesSearchResponseSearchResponse = nil
		} else {
			return nil // data stored in dst.DtoResponsesSearchResponseSearchResponse, return on the first match
		}
	} else {
		dst.DtoResponsesSearchResponseSearchResponse = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SearchduplicatesbyoriginalidPostResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *SearchduplicatesbyoriginalidPostResponse) MarshalJSON() ([]byte, error) {
	if src.ClusteringSearchResponse != nil {
		return json.Marshal(&src.ClusteringSearchResponse)
	}

	if src.DtoResponsesSearchResponseSearchResponse != nil {
		return json.Marshal(&src.DtoResponsesSearchResponseSearchResponse)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableSearchduplicatesbyoriginalidPostResponse struct {
	value *SearchduplicatesbyoriginalidPostResponse
	isSet bool
}

func (v NullableSearchduplicatesbyoriginalidPostResponse) Get() *SearchduplicatesbyoriginalidPostResponse {
	return v.value
}

func (v *NullableSearchduplicatesbyoriginalidPostResponse) Set(val *SearchduplicatesbyoriginalidPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchduplicatesbyoriginalidPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchduplicatesbyoriginalidPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchduplicatesbyoriginalidPostResponse(val *SearchduplicatesbyoriginalidPostResponse) *NullableSearchduplicatesbyoriginalidPostResponse {
	return &NullableSearchduplicatesbyoriginalidPostResponse{value: val, isSet: true}
}

func (v NullableSearchduplicatesbyoriginalidPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchduplicatesbyoriginalidPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


