/*
NewsCatcher-V3 Production API

Testing AuthorsApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package newscatcherapi

import (
    "testing"
    // "github.com/stretchr/testify/assert"
    // "github.com/stretchr/testify/require"
    // newscatcherapi "github.com/konfig-dev/newscatcher-go-sdk"
)

func Test_newscatcherapi_AuthorsApiService(t *testing.T) {

    // configuration := newscatcherapi.NewConfiguration()
    // configuration.SetHost("http://127.0.0.1:4010")
    /* 
    configuration.SetApiKey("X_API_TOKEN")
    client := newscatcherapi.NewAPIClient(configuration)
    */

    t.Run("Test AuthorsApiService Get", func(t *testing.T) {
        /* TODO: ENG-1367 Fix parameter values for Go SDK generated tests
        request := client.AuthorsApi.Get(
            "authorName_example",
        )
        request.NotAuthorName("notAuthorName_example")
        request.Sources()
        request.PredefinedSources()
        request.NotSources()
        request.Lang()
        request.NotLang()
        request.Countries()
        request.NotCountries()
        request.From("from_example")
        request.To("to_example")
        request.PublishedDatePrecision("publishedDatePrecision_example")
        request.ByParseDate(false)
        request.SortBy(""relevancy"")
        request.RankedOnly("rankedOnly_example")
        request.FromRank(56)
        request.ToRank(56)
        request.IsHeadline(true)
        request.IsOpinion(true)
        request.IsPaidContent(true)
        request.ParentUrl()
        request.AllLinks()
        request.AllDomainLinks()
        request.WordCountMin(56)
        request.WordCountMax(56)
        request.Page(1)
        request.PageSize(100)
        request.IncludeNlpData(true)
        request.HasNlp(true)
        request.Theme("theme_example")
        request.NotTheme("notTheme_example")
        request.NerName("nerName_example")
        request.TitleSentimentMin(8.14)
        request.TitleSentimentMax(8.14)
        request.ContentSentimentMin(8.14)
        request.ContentSentimentMax(8.14)
        request.IptcTags()
        request.NotIptcTags()
        request.IabTags()
        request.NotIabTags()
        
        resp, httpRes, err := request.Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)
        */
    })

    t.Run("Test AuthorsApiService Post", func(t *testing.T) {
        /* TODO: ENG-1367 Fix parameter values for Go SDK generated tests
        
        authorSearchRequest := *newscatcherapi.NewAuthorSearchRequest(
            "null",
        )
        authorSearchRequest.SetNotAuthorName("null")
        authorSearchRequest.SetSources(null)
        authorSearchRequest.SetPredefinedSources(null)
        authorSearchRequest.SetNotSources(null)
        authorSearchRequest.SetLang(null)
        authorSearchRequest.SetNotLang(null)
        authorSearchRequest.SetCountries(null)
        authorSearchRequest.SetNotCountries(null)
        authorSearchRequest.SetFrom("null")
        authorSearchRequest.SetTo("null")
        authorSearchRequest.SetPublishedDatePrecision("null")
        authorSearchRequest.SetByParseDate(false)
        authorSearchRequest.SetSortBy("relevancy")
        authorSearchRequest.SetRankedOnly("null")
        authorSearchRequest.SetFromRank(null)
        authorSearchRequest.SetToRank(null)
        authorSearchRequest.SetIsHeadline(null)
        authorSearchRequest.SetIsOpinion(null)
        authorSearchRequest.SetIsPaidContent(null)
        authorSearchRequest.SetParentUrl(null)
        authorSearchRequest.SetAllLinks(null)
        authorSearchRequest.SetAllDomainLinks(null)
        authorSearchRequest.SetWordCountMin(null)
        authorSearchRequest.SetWordCountMax(null)
        authorSearchRequest.SetPage(1)
        authorSearchRequest.SetPageSize(100)
        authorSearchRequest.SetIncludeNlpData(null)
        authorSearchRequest.SetHasNlp(null)
        authorSearchRequest.SetTheme("null")
        authorSearchRequest.SetNotTheme("null")
        authorSearchRequest.SetNerName("null")
        authorSearchRequest.SetTitleSentimentMin(null)
        authorSearchRequest.SetTitleSentimentMax(null)
        authorSearchRequest.SetContentSentimentMin(null)
        authorSearchRequest.SetContentSentimentMax(null)
        authorSearchRequest.SetIptcTags(null)
        authorSearchRequest.SetNotIptcTags(null)
        authorSearchRequest.SetIabTags(null)
        authorSearchRequest.SetNotIabTags(null)
        
        request := client.AuthorsApi.Post(
            authorSearchRequest,
        )
        
        resp, httpRes, err := request.Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)
        */
    })

}