/*
NewsCatcher-V3 Production API

Testing SearchLinkApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package newscatcherapi

import (
    "testing"
    // "github.com/stretchr/testify/assert"
    // "github.com/stretchr/testify/require"
    // newscatcherapi "github.com/konfig-dev/newscatcher-go-sdk"
)

func Test_newscatcherapi_SearchLinkApiService(t *testing.T) {

    // configuration := newscatcherapi.NewConfiguration()
    // configuration.SetHost("http://127.0.0.1:4010")
    /* 
    configuration.SetApiKey("X_API_TOKEN")
    client := newscatcherapi.NewAPIClient(configuration)
    */

    t.Run("Test SearchLinkApiService Get", func(t *testing.T) {
        /* TODO: ENG-1367 Fix parameter values for Go SDK generated tests
        request := client.SearchLinkApi.Get(
        )
        request.Ids()
        request.Links()
        request.From("from_example")
        request.To("to_example")
        request.Page(1)
        request.PageSize(100)
        
        resp, httpRes, err := request.Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)
        */
    })

    t.Run("Test SearchLinkApiService Post", func(t *testing.T) {
        /* TODO: ENG-1367 Fix parameter values for Go SDK generated tests
        
        searchURLRequest := *newscatcherapi.NewSearchURLRequest()
        searchURLRequest.SetIds(null)
        searchURLRequest.SetLinks(null)
        searchURLRequest.SetFrom("null")
        searchURLRequest.SetTo("null")
        searchURLRequest.SetPage(1)
        searchURLRequest.SetPageSize(100)
        
        request := client.SearchLinkApi.Post(
            searchURLRequest,
        )
        
        resp, httpRes, err := request.Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)
        */
    })

}